from .download.downloader import download
from .load.loader import DatasetLoader, join_datasets
from .split.splitter import train_test_validate
from .dataset.dataset import (
    Dataset,
    load,
)

# '_version.py' will be generated by hatchling once the switch away from
# setuptools.py is finished
try:
    from ._version import __version__
except ImportError:
    __version__ = '0.1.40'
try:
    from ._version import __version_tuple__
except ImportError:
    __version_tuple__ = (0, 1, 40)

from .utils.utils import version