from .download.downloader import download
from .split.splitter import train_test_validate
from .dataset.dataset import (
    Dataset,
    load,
)

# '_version.py' will be generated by hatchling once the switch away from
# setuptools.py is finished
from ._version import __version__
from ._version import __version_tuple__


from .utils.utils import version
from .utils.utils import list_datasets