'''
This is a script that leverages PHarmacogx R package as well as the curve.py script
to collect all the data into a single file for CANDLE
_author_='Sara Gosline'
_email_ = 'sara.gosline@pnnl.gov'
'''

import pandas as pd
import os

##we want to build the datasets in order, because of how we pull the drug information
datasets = ['ctrpv2','prism','tavor','fimm','beatAML','UHNBreast','gbm','gray','pdtx']

#these are the files that are complete so far
datasets = ['prism','fimm','ctrpv2','nci60']
#empty list of files

#the following are experiment specific and can be duplicated
dose_files = []
gex_files = []
mut_files = []


'''
Step 1: we iterate through every dataset and pull it from pharmacogx
'''
for dat in datasets:
  print("Analyzing "+dat+' dataset')
  
  #this will generate all the files below except the summary stats (which are generated by python)
  rcmd = 'Rscript pgx/'+dat+'dataFormat.R '+samp_file+' '+gene_file+' '+drug_file
  
  ##this will fit the curve
  dose_rep = 'python ../curve/fit_curve.py --input '+dat+'doseResponse.csv --output '+dat+'drugSummaryStats.csv'

  ##run the commands
  print(rcmd)
  os.system(rcmd)
  if(os.path.exists(dat+'geneExpression.csv')):
    gex_files.append(dat+'geneExpression.csv')
 # cnv_files.append(dat+'copyNumber.csv')
#  mut_files.append(dat+'mutations.tsv')
  
  print('Now fitting curves...')
  print(dose_rep)
  os.system(dose_rep)
  
  ##add the files to the list
  dose_files.append(dat+'drugSummaryStats.csv')

##now we must append everything into a single file - one for gex
##and one for dose response stats
  
