---
title: "Figure 4 ex vivo results"
author: "Sara Gosline"
date: "2025-06-02"
output: html_document
---

This figure focuses on the ex vivo results

## Data and packages

First we get the packages loaded and logged into synapse.
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo  =  TRUE)
library(tidyverse)
library(ggplot2)
source('coderdataResultsFunctions.R')

```


The data has been uploaded by natasha and can be downloaded as follows.

```{r download data}

  cdres <- getModelPerformanceData()

  ecdres <- subset(cdres,trg %in% exvivo)


```

## Figure 4A


```{r}
metrics <- c('scc','pcc')
exres = lapply(metrics,function(x) {
  res<-ridgelineMetricPlots(x, ecdres,'cellline')
  cowplot::plot_grid(res$src,res$trg)
  ggsave(paste0('exvivo',x,'_ridglines.pdf'),height = 8,width = 10)
  return(res$src)
  })

print(exres)
```

Now we can confirm that the datasets follow the same pattern. 

```{r dataset samples}


plot<-calcSourceStatistics('scc',ecdres)


ggsave('exVivoSamplePerformanceCorrelation.pdf',plot, height=12,width=5)
print(plot)

```

## Create funtion to dive in



```{r}

```
