title: CoderData
baseurl: "/coderdata" # the subpath of your site, e.g. /blog
url: "https://pnnl-compbio.github.io" # the base hostname & protocol for your site

source: docs

# Build settings
markdown: kramdown
theme: null # No theme is used since you are specifying your own layouts
layouts_dir: _layouts # Specifies where to find the layout templates