---
title: "Untitled"
author: "JJ"
date: "2023-09-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("DreamAI")

```


```{r DREAMAI-example}

# Define the URL
url <- "https://raw.githubusercontent.com/WangLab-MSSM/DreamAI/master/Code/data/datapnnl.RData"

# Define the local filename to save the file
local_filename <- "datapnnl.RData"

# Download the file
download.file(url, destfile = local_filename, method = "curl")

# Load the RData file into your environment
load(local_filename)

datapnnl.rm.ref

data<-datapnnl.rm.ref[1:100,1:21]
impute<- DreamAI(data,k=10,maxiter_MF = 10, ntree = 100,maxnodes = NULL,maxiter_ADMIN=30,tol=10^(-2),gamma_ADMIN=NA,gamma=50,CV=FALSE,fillmethod="row_mean",maxiter_RegImpute=10,conv_nrmse = 1e-6,iter_SpectroFM=40, method = c("KNN", "MissForest", "ADMIN", "Birnn", "SpectroFM", "RegImpute"),out="Ensemble")
impute$Ensemble

```


```{r CellLine-Data}
# Read the proteomics data
proteomics_data_original <- read.csv("proteomics_restructure.tsv",sep="\t")

proteomics_data <- proteomics_data_original
# Rename columns and remove unnecessary rows
colnames(proteomics_data) <- as.character(proteomics_data[2, ])
proteomics_data <- proteomics_data[-c(1,2), ]
proteomics_data
# Remove the first column and set rownames
rownames(proteomics_data) <- proteomics_data[,1]
proteomics_data <- proteomics_data[,-1]
proteomics_data[] <- lapply(proteomics_data, as.numeric)

# Remove columns with more than 90% NA values
remove_cols <- apply(proteomics_data, 2, function(column) {
  sum(is.na(column)) > 0.9 * length(column)
})

proteomics_filtered <- proteomics_data[, !remove_cols]

# Convert the filtered data to a matrix and impute missing values
matrix_proteomics <- as.matrix(proteomics_filtered)

imputed_result <- DreamAI(matrix_proteomics, k=10, maxiter_MF = 10, ntree = 100, maxnodes = NULL, maxiter_ADMIN=30, tol=10^(-2), gamma_ADMIN=NA, gamma=50, CV=FALSE, fillmethod="row_mean", maxiter_RegImpute=10, conv_nrmse = 1e-6, iter_SpectroFM=40, method = c("KNN"), out="Ensemble")

# Convert imputed results to a data frame
proteomics_imputed <- as.data.frame(imputed_result$Ensemble)


#### Update header to match original

ENSG_mapping <- colnames(proteomics_data_original)
entrez_mapping <- as.character(proteomics_data_original[1,])
gene_mapping <- as.character(proteomics_data_original[2,])
imputed_gene_mapping <- colnames(proteomics_imputed)

# Match the gene mappings
matched_indices <- match(imputed_gene_mapping, gene_mapping)

# Update the mappings based on matched indices
imputed_ENSG_mapping <- ENSG_mapping[matched_indices]
imputed_entrez_mapping <- entrez_mapping[matched_indices]

# Rebind data for updated mapping
proteomics_imputed <- rbind(imputed_gene_mapping, proteomics_imputed)
proteomics_imputed <- rbind(imputed_entrez_mapping, proteomics_imputed)
proteomics_imputed <- rbind(imputed_ENSG_mapping, proteomics_imputed)
proteomics_imputed <- cbind(RowNames = rownames(proteomics_imputed), proteomics_imputed)
# 
rownames(proteomics_imputed) <- NULL
colnames(proteomics_imputed) <- NULL
proteomics_imputed[1:3,1] <- NA
# proteomics_imputed

proteomics_imputed
#Save the results
# 
write.table(proteomics_imputed, "proteomics_restructure_with_knn_impute.tsv",sep="\t",row.names = FALSE,col.names = FALSE,na = "",quote = FALSE)



```




