name: Build docker images

on:
  push:
    branches:
      - '**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-cellline-omics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push broad sanger omics
        uses: docker/build-push-action@v3
        with:
          file: ./build/docker/Dockerfile.broad_sanger_omics
          tags: sgosline/broad-sanger-omics:latest
          push: true
          platforms: linux/amd64,linux/arm64
  build-cellline-exp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push broad sanger experiment
        uses: docker/build-push-action@v3
        with:
          file: ./build/docker/Dockerfile.broad_sanger_exp
          tags: sgosline/broad-sanger-exp:latest
          push: true
          platforms: linux/amd64,linux/arm64
  build-genes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}   
      - name: Build and push genes
        uses: docker/build-push-action@v3
        with:
          file: ./build/docker/Dockerfile.genes
          tags: sgosline/genes:latest
          push: true
          platforms: linux/amd64,linux/arm64
  build-hcmi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push hcmi
        uses: docker/build-push-action@v3
        with:
          file: ./build/docker/Dockerfile.hcmi
          tags: sgosline/hcmi:latest
          push: true
          platforms: linux/amd64,linux/arm64
  build-cptac:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  
      - name: Build and push cptac
        uses: docker/build-push-action@v3
        with:
          file: ./build/docker/Dockerfile.cptac
          tags: sgosline/cptac:latest
          push: true
          platforms: linux/amd64,linux/arm64
  build-mpnst:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  
      - name: Build and push mpnst
        uses: docker/build-push-action@v3
        with:
          file: ./build/docker/Dockerfile.mpnst
          tags: sgosline/mpnst:latest
          push: true
          platforms: linux/amd64,linux/arm64
  build-beataml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  
      - name: Build and push beataml
        uses: docker/build-push-action@v3
        with:
          file: ./build/docker/Dockerfile.beataml
          tags: sgosline/beataml:latest
          push: true
          platforms: linux/amd64,linux/arm64
  build-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  
      - name: Build and push upload
        uses: docker/build-push-action@v3
        with:
          file: ./build/docker/Dockerfile.upload
          tags: sgosline/upload:latest
          push: true
          platforms: linux/amd64,linux/arm64        
  

