name: Build docker images

on:
  push:
    tags:
        - '*'  # Triggers the workflow only on version tags
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-cell-line-omics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push broad sanger omics
        uses: docker/build-push-action@v3
        with:
          file: ./build/docker/Dockerfile.broad_sanger_omics
          tags: |
            sgosline/broad-sanger-omics:latest
            sgosline/broad-sanger-omics:${{ github.ref_name }}
          push: true
          platforms: linux/amd64

  build-cell-line-exp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push broad sanger experiment
        uses: docker/build-push-action@v3
        with:
          file: ./build/docker/Dockerfile.broad_sanger_exp
          tags: |
            sgosline/broad-sanger-exp:latest
            sgosline/broad-sanger-exp:${{ github.ref_name }}
          push: true
          platforms: linux/amd64

  # Repeat the same tag update for the remaining steps:
  build-genes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push genes
        uses: docker/build-push-action@v3
        with:
          file: ./build/docker/Dockerfile.genes
          tags: |
            sgosline/genes:latest
            sgosline/genes:${{ github.ref_name }}
          push: true
          platforms: linux/amd64

  build-hcmi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push hcmi
        uses: docker/build-push-action@v3
        with:
          file: ./build/docker/Dockerfile.hcmi
          tags: |
            sgosline/hcmi:latest
            sgosline/hcmi:${{ github.ref_name }}
          push: true
          platforms: linux/amd64

  build-cptac:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push cptac
        uses: docker/build-push-action@v3
        with:
          file: ./build/docker/Dockerfile.cptac
          tags: |
            sgosline/cptac:latest
            sgosline/cptac:${{ github.ref_name }}
          push: true
          platforms: linux/amd64

  build-mpnst:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push mpnst
        uses: docker/build-push-action@v3
        with:
          file: ./build/docker/Dockerfile.mpnst
          tags: |
            sgosline/mpnst:latest
            sgosline/mpnst:${{ github.ref_name }}
          push: true
          platforms: linux/amd64

  build-beataml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push beataml
        uses: docker/build-push-action@v3
        with:
          file: ./build/docker/Dockerfile.beataml
          tags: |
            sgosline/beataml:latest
            sgosline/beataml:${{ github.ref_name }}
          push: true
          platforms: linux/amd64

  build-pancpdo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push pancpdo
        uses: docker/build-push-action@v3
        with:
          file: ./build/docker/Dockerfile.pancpdo
          tags: |
            sgosline/pancpdo:latest
            sgosline/pancpdo:${{ github.ref_name }}
          push: true
          platforms: linux/amd64

  build-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push upload
        uses: docker/build-push-action@v3
        with:
          file: ./build/docker/Dockerfile.upload
          tags: |
            sgosline/upload:latest
            sgosline/upload:${{ github.ref_name }}
          push: true
          platforms: linux/amd64
