name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python for GitHub
      if: github.event_name != 'push' || github.repository != 'owner/repo'
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with ruff
      run: |
        # stop the build if there are Python syntax errors or undefined names
        ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
        # default set of ruff rules with GitHub Annotations
        ruff --format=github --target-version=py37 .

    - name: Test with pytest
      run: |
        pytest

    - name: Data Generation and Push
      run: |
        echo "Starting with copy number"
        python hcmi/getHCMIData.py -m copy_number_manifest_gdc.txt -t copy_number -o copy_number_hcmi.csv

