name: CI

on:
  push:
    branches:
      - JJ_hcmi_branch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python for GitHub
      if: github.event_name != 'push' || github.repository != 'owner/repo'
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Data Generation and Push
      run: |
        echo "Starting with copy number"
        python hcmi/getHCMIData.py -m copy_number_manifest_gdc.txt -t copy_number -o copy_number_hcmi.csv

