name: "Sphinx: Render docs"

on:
  push:
    tags:
          - '*'  # Triggers the workflow only on version tags
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        publish: true
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.DOCSITE_TOKEN }}
        publish_dir: docs/build/html