name: Sphinx-docs

on:
  push:
    branches:
      - main
      - gh-pages
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build HTML
      run: python -m sphinx.cmd.build -M html docs/source docs/build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/

    - name: Deploy
      # uses: sphinx-notes/pages@v3
      # with:
      #   publish: true
      
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.DOCSITE_TOKEN }}
        publish_dir: docs/build/html
