name: Python package tests

on:
  push:
    branches: [ package_dev_JJ ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-file: [
          'test_download_and_load_beataml.py', 
          'test_download_and_load_depmap.py', 
          'test_download_beataml_cli.py', 
          'test_download_depmap_cli.py',
          'test_download_and_load_cptac.py', 
          'test_download_and_load_hcmi.py', 
          'test_download_cptac_cli.py', 
          'test_download_hcmi_cli.py'
        ]
    outputs:
      result: ${{ steps.test-outcome.outcome }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-xdist


    - name: Install as package
      run: |
        pip install .

    - name: Run test
      id: test-outcome
      run: |
        pytest -n 4 tests/${{ matrix.test-file }}
